<a href="https://colab.research.google.com/github/MaheepSeharawat/practice_for_data_science/blob/main/NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
x=np.zeros(10,dtype=int)
x[4]=1
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
a=int(input("enter number a"))
b=int(input("enter number b"))
z=np.arange(a*b).reshape(a,b)
print(float(np.mean(z)))
z

KeyboardInterrupt: Interrupted by user

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here
k=np.zeros(a*b,dtype=int).reshape(a,b)
for i in range(len(k[0])):

  k[0,i]=1
  k[b-1]=1
for i in range(b):
  k[i,0]=1
  k[i,a-1]=1
k

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
x=np.linspace(0,1,12)
x=x[1:-1]
x

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#can't write code for an identity matrix bcoz it can only be created for n*n matrix.

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
l=np.linspace(0,4,25)
l

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
import math
arr=np.random.randint(101,size=(10,2))
x=int(input("enter the x cordinate "))
y=int(input("enter y coordinate "))
dist_arr=[]
given_pt=[x,y]
for i in arr:
  dist=(i[0]-x)**2+(i[1]-y)**2
  dist_arr.append(int(math.sqrt(dist)))
dist_arr

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
x=np.unravel_index(99,(6,7,8))
x

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
x=input().split()
z=np.array(x,dtype=float)
z[::-1]

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
x = np.array(eval(input()))
print("elements_count : ", np.size(x))

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here
x=np.array(eval(input()))
k= np.ndim(x)
if k==1:
  j=[]
  for i in x:
    val=math.exp(i)
    j.append(val)
  d=sum(j)
  l=[]
  for i in j:
    o=i/d
    l.append(o)
  print(l)
else:
  print("error")

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
def vertical_stack(*arrays):
    # Check at least one array
    if len(arrays) == 0:
        raise ValueError("At least one array required")

    # Validate all inputs
    for arr in arrays:
        if not isinstance(arr, np.ndarray):
            raise TypeError("All inputs must be NumPy arrays")

    # Perform vertical stacking
    return np.vstack(arrays)
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
b = np.array([[1,1,1,1,1],[1,1,1,1,1]])

print(vertical_stack(a, b))

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
from datetime import datetime
def date_array(start, end):
    # Type check
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Both inputs must be strings")

    try:
        # Validate format (YYYY-M-D works with %Y-%m-%d)
        d1 = datetime.strptime(start, "%Y-%m-%d")
        d2 = datetime.strptime(end, "%Y-%m-%d")

        # Ensure same year
        if d1.year != d2.year:
            raise ValueError("Dates must be in the same year")

        # Convert to numpy datetime64
        start_np = np.datetime64(start)
        end_np = np.datetime64(end)

        # Include end date → +1 day
        dates = np.arange(start_np, end_np + 1, dtype='datetime64[D]')

        return dates

    except ValueError:
        raise ValueError("Invalid date format")
date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

print(f"Enter the {rows * cols} elements separated by space:")

elements = list(map(int, input().split()))
matrix = np.array(elements).reshape(rows, cols)
l=[]
for i in matrix:
  z=np.mean(i)
  l.append(z)
k=np.ones(np.shape(matrix))
for i in range(len(l)):
  k[i]*=l[i]
print(matrix-k)


Enter number of rows: 2
Enter number of columns: 2
Enter the 4 elements separated by space:
1 0 1 0
[[ 0.5 -0.5]
 [ 0.5 -0.5]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here

In [ ]:
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

print(f"Enter the {rows * cols} elements separated by space:")

elements = list(map(int, input().split()))
matrix = np.array(elements).reshape(rows, cols)
print(matrix)
matrix[:, [0, 1]] = matrix[:, [1, 0]]
matrix

Enter number of rows: 2
Enter number of columns: 2
Enter the 4 elements separated by space:
0 1 0 1
[[0 1]
 [0 1]]


array([[1, 0],
       [1, 0]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

print(f"Enter the {rows * cols} elements separated by space:")

elements = list(map(int, input().split()))
matrix = np.array(elements).reshape(rows, cols)
z=np.shape(matrix)
print("before",matrix)
for i in range(z[0]):
  for j in range(z[1]):
    if matrix[i][j]%2==1:
      matrix[i][j]=-1
    else:
      continue
print("after",matrix)

Enter number of rows: 2
Enter number of columns: 2
Enter the 4 elements separated by space:
1 3 5 8
before [[1 3]
 [5 8]]
after [[-1 -1]
 [-1  8]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [5]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
print(np.maximum(a,b))

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [6]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[8284, 7013, 9331, 1659,  503],
       [6816,  533,  660, 1459, 6122],
       [7306, 1398, 1449, 6152, 3310],
       [7335, 2334, 3717, 3743,  373],
       [2725, 3287, 6434, 3015, 8262],
       [3720, 6108, 8853, 7409, 3987],
       [2657, 6257, 9412, 8217, 3896],
       [8035, 8023, 3960, 8206, 6868]])

In [17]:
#Code here
data1=arr1[:,0]
data2=arr1[:,2]
data3=arr1[:,4]
print(data1)
data1=(data1-np.min(data1))/(np.max(data1)-np.min(data1))
data2=(data2-np.min(data2))/(np.max(data2)-np.min(data2))
data3=(data3-np.min(data3))/(np.max(data3)-np.min(data3))
data1
print(type(data1))

[8284 6816 7306 7335 2725 3720 2657 8035]
<class 'numpy.ndarray'>


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [11]:
#Code here
def largest_n_number(arr,n):
  if isinstance(arr,np.ndarray):
    if np.ndim(arr)==1:
      max1=np.max(arr[0:n])
      return max1

  else:
    return "fuckoff"
arr=(12,34,40,7,1,0)
arr=np.array(arr)
n=3
print(largest_n_number(arr,n))


40
[12 34 40  7  1  0 12 34 40  7  1  0]


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [20]:
#code here
a = list(map(int, input().split()))
a = np.array(a)
n = len(a)
repeat1=np.repeat(a,n)
tiled=np.tile(a,n)
final=np.concatenate((tiled,repeat1))
print(final)


1 2 3
[1 2 3 1 2 3 1 2 3 1 1 1 2 2 2 3 3 3]
